data:
    type: "LLdataset"
    train_dataset: "EVUP"
    val_dataset: "EVUP"
    patch_size: 256
    channels: 3
    num_workers: 16
    data_dir:  "/media/anil/New Volume5/research/vidhi/dll/dll/data"

    ckpt_dir: "ckpts/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 3
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: sigmoid
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 16
    n_epochs: 500
    validation_freq: 232

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8


