data:
    type: "LLdataset"
    train_dataset: "LSUI"
    val_dataset: "LSUI"
    patch_size: 256
    channels: 3
    dwt_levels: 2
    num_workers: 0
    data_dir: "/kaggle/input/lsui-large-scale-underwater-image-dataset"
    ckpt_dir: "ckpt/UNet_LSUI_14_07_All_Losses"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 16
    n_epochs: 500
    validation_freq: 1000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8

wandb:
    token: "8285c1e86ba66976957cd9bdbae9e646b37bba8f"
    name: "UNet_14_07_AllLosses_oldDWT"
    resume: true
    id: 'onmy5aui'